### ISSUE TITLE
Some zones missing temperature data

### ISSUE THREAD

**Issue by michaeleverist** [awulf/Actron485#3]
Hello - firstly thank you for the fantastic work on this - I have had no issues implementing this per data you provided.  

I'm not sure where the data is missing from, but the current temperature is not displaying for 5 of the zones:

![Image](https://github.com/user-attachments/assets/6004f6fb-0d43-4d60-ad30-9d8aef1abe32)

Looking at the logs, the data for the missing zones isnt being picked up in the ~1.5 second stream i.e Zones 2,3 and 4 have:

```
[22:02:22][D][actron485.climate:027]: M: Zone: 2, Set Point: 23.50, Temp: 23.80, SP Range: 19.50-23.50, Zone: Off, Damper Pos: 0%
[22:02:22][D][actron485.climate:027]: 82 EE 00 27 2F 2F 0A    
[22:02:23][D][actron485.climate:027]:    
[22:02:23][D][actron485.climate:027]: C: Zone: 2, Set Point: 23.50, Temp: 23.80(Pre:23.80), Mode: Off  
[22:02:23][D][actron485.climate:027]: C2 2F 02 0C 00   
```

For the zones with no data, each loop of the status message shows the following for one of the missing zones, then on the next iteration will show Zone 5, then 6 etc  :

```
[22:02:23][D][actron485.climate:027]: C: Zone: 1, Init Zone0.00
[22:02:23][D][actron485.climate:027]: C1 00 D1 00 6D 
```

I'm able to control all zones via home assistant and I can see the individual zone temperatures using Mike McGuires addon for actron connect so I know the data is at least working in those zones.

Logs attached

[logs_actron-aircon_logs (1).txt](https://github.com/user-attachments/files/19823065/logs_actron-aircon_logs.1.txt)

**Comment by awulf** [comment]
Hi, sorry about the delay, I didn't have email notifications turned on, so didn't see this issue.

Can you post your Actron ESPHome Configuration? And what model your system is? What are your zone wall controllers e.g. mine are LM-ZC-2W. Any seperate temperature sensors? Any errors showing on those wall controllers?
Based on the logs, and on how I understand this system to work. The 0 message is
```
[22:03:40][D][actron485.climate:027]: C: Zone: 7, Init Zone0.00
[22:03:40][D][actron485.climate:027]: C7 00 D1 00 67 
```
From https://github.com/awulf/Actron485/blob/main/docs/ZoneMessaging.txt Is:
`0 - Requesting Zone: set to 1 on power up for configuring the wall controller, this message comes from master when it can't see responses from zone wall controller`
From that understanding of mine, those zones shouldn't be working at all, as they aren't responding to the initialisation request on there RS485 bus that all the zone controllers should be on.
My only thought is if they are working, maybe your system has a second data bus for the other set of zones.

**Comment by michaeleverist** [comment]
Hi there, thanks for taking a look at this.

ESPHome config is as follows:
```
substitutions:
  device_name: "actron-aircon"
  friendly_name: "actron_aircon"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: '/config/Actron485/components'

#################################
esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  platformio_options:
    lib_extra_dirs: /config/
  libraries:
    Actron485   

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret backup_ap_password
api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

logger:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
     
captive_portal:

switch:
  - platform: restart
    name: "${friendly_name} REBOOT"  

#################################

# Adds fan component per zone (required)
fan:
# UART settings for Actron485 (required)
uart:
  rx_pin: GPIO18 
  tx_pin: GPIO19 
  baud_rate: 4800

climate:
  - platform: actron485
    name: "Actron Climate Controller"
    write_enable_pin: GPIO4 # Write Enable pin for the RS-485 communication  WAS SET to 25!
    esp_fan_available: true # For Systems with ESP Auto mode, adds Auto fan mode.
    ultima: # For ULTIMA Systems only, adds climate controls per zone.
      available: true
      adjust_master_target: true # Adjust master target temperature to allow the targeted zone temperature.
    logging_mode: ALL
    # logging_mode: CHANGE
    zones:
      - number: 1
        name: "1 Main Bedroom"
      - number: 2
        name: "2 Ella Bedroom"
      - number: 3
        name: "3 Study"
      - number: 4
        name: "4 Maia Bedroom"
      - number: 5
        name: "5 Rumpus Room"
      - number: 6
        name: "6 Living Room"
      - number: 7
        name: "7 Theatre"
      - number: 8
        name: "8 Guest Bedroom"
```

I think you might be right about two buses but it still doesnt make sense to me - we have 2 zone controllers: an LM7 and an LM24 and all temperatures are visible from either wall controller.

There arent any errors on either controller and as i mentioned using the actron connect proxy all the zone temps are visible.

Only other relevant information is that some rooms have the little wall controls to turn zone on/off and set temp where others just have a temp sensor, however there is no correlation between the zones with sensors only and the missing info.
